/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.LoginAndSignUp.src.loginandsignup;

import java.awt.Color;
import Frontend.LoginAAbsoluteConstraints;

import Backend.Models.Usuario;

/**
 *
 * @author audre
 */
public class MenuUsr extends javax.swing.JFrame {
    public Usuario usuario;
    /**
     * Creates new form MenuUsr
     */
    public MenuUsr() {
        initComponents();
        
    }
    public MenuUsr(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SALIR = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HOME = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BUSCAR = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen3.png"))); // NOI18N
        jPanel1.add(jLabel4, new AbsoluteConstraints(110, 30, 140, 150));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("PEPE");
        jPanel1.add(jLabel3, new AbsoluteConstraints(150, 180, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new AbsoluteConstraints(0, 0, 360, 270));

        SALIR.setBackground(new java.awt.Color(247, 247, 247));
        SALIR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SALIRMouseMoved(evt);
            }
        });
        SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SALIRMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SALIRMouseExited(evt);
            }
        });
        SALIR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\audre\\OneDrive\\Documentos\\NetBeansProjects\\LoginAndSignUp\\src\\icon\\Imagen6.png")); // NOI18N
        SALIR.add(jLabel7, new AbsoluteConstraints(20, 30, -1, 50));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("SALIR");
        SALIR.add(jLabel8, new AbsoluteConstraints(86, 50, 70, 20));

        jPanel1.add(SALIR, new AbsoluteConstraints(0, 490, 360, 110));

        HOME.setBackground(new java.awt.Color(247, 247, 247));
        HOME.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HOMEMouseMoved(evt);
            }
        });
        HOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOMEMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOMEMouseExited(evt);
            }
        });
        HOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen4.png"))); // NOI18N
        HOME.add(jLabel5, new AbsoluteConstraints(20, 30, -1, 50));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("HOME");
        HOME.add(jLabel6, new AbsoluteConstraints(90, 50, 70, 20));

        jPanel1.add(HOME, new AbsoluteConstraints(0, 270, 360, 110));

        BUSCAR.setBackground(new java.awt.Color(247, 247, 247));
        BUSCAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BUSCARMouseMoved(evt);
            }
        });
        BUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUSCARMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BUSCARMouseExited(evt);
            }
        });
        BUSCAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen5.png"))); // NOI18N
        BUSCAR.add(jLabel9, new AbsoluteConstraints(20, 30, -1, 50));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("BUSCA A UN AMIGO/A");
        BUSCAR.add(jLabel10, new AbsoluteConstraints(86, 50, 230, 20));

        jPanel1.add(BUSCAR, new AbsoluteConstraints(0, 380, 360, 110));

        getContentPane().add(jPanel1, new AbsoluteConstraints(0, 0, -1, 780));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new AbsoluteConstraints(320, 0, 1180, 80));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 153));
        jLabel11.setText("BIENVENIDOS A PAW CONNECT");
        jPanel2.add(jLabel11, new AbsoluteConstraints(230, 40, -1, -1));

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Recomendaciones que podrian enamorarte");
        jPanel2.add(jLabel13, new AbsoluteConstraints(260, 110, -1, -1));

        jPanel19.setBackground(new java.awt.Color(255, 236, 236));
        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(247, 247, 247));
        jButton14.setForeground(new java.awt.Color(51, 51, 51));
        jButton14.setText("Editar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton14, new AbsoluteConstraints(20, 110, -1, 30));

        jButton15.setBackground(new java.awt.Color(247, 247, 247));
        jButton15.setForeground(new java.awt.Color(51, 51, 51));
        jButton15.setText("Eliminar");
        jPanel19.add(jButton15, new AbsoluteConstraints(20, 150, -1, 30));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel20.add(jLabel33, new AbsoluteConstraints(0, 0, 220, 160));

        jPanel19.add(jPanel20, new AbsoluteConstraints(110, 20, 220, 160));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jLabel30, new AbsoluteConstraints(0, 0, 70, 70));

        jPanel19.add(jPanel21, new AbsoluteConstraints(20, 20, 70, 70));

        jPanel2.add(jPanel19, new AbsoluteConstraints(540, 390, 350, 200));

        jPanel13.setBackground(new java.awt.Color(255, 236, 236));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(247, 247, 247));
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("Editar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton10, new AbsoluteConstraints(20, 110, -1, 30));

        jButton11.setBackground(new java.awt.Color(247, 247, 247));
        jButton11.setForeground(new java.awt.Color(51, 51, 51));
        jButton11.setText("Eliminar");
        jPanel13.add(jButton11, new AbsoluteConstraints(20, 150, -1, 30));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jLabel34, new AbsoluteConstraints(0, 0, 220, 160));

        jPanel13.add(jPanel14, new AbsoluteConstraints(110, 20, 220, 160));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jLabel28, new AbsoluteConstraints(0, 0, 70, 70));

        jPanel13.add(jPanel15, new AbsoluteConstraints(20, 20, 70, 70));

        jPanel2.add(jPanel13, new AbsoluteConstraints(540, 170, 350, 200));

        jPanel16.setBackground(new java.awt.Color(255, 236, 236));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setBackground(new java.awt.Color(247, 247, 247));
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.setText("Editar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton12, new AbsoluteConstraints(20, 110, -1, 30));

        jButton13.setBackground(new java.awt.Color(247, 247, 247));
        jButton13.setForeground(new java.awt.Color(51, 51, 51));
        jButton13.setText("Eliminar");
        jPanel16.add(jButton13, new AbsoluteConstraints(20, 150, -1, 30));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jLabel32, new AbsoluteConstraints(0, 0, 220, 160));

        jPanel16.add(jPanel17, new AbsoluteConstraints(110, 20, 220, 160));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jLabel29, new AbsoluteConstraints(0, 0, 70, 70));

        jPanel16.add(jPanel18, new AbsoluteConstraints(20, 20, 70, 70));

        jPanel2.add(jPanel16, new AbsoluteConstraints(120, 390, 350, 200));

        jPanel4.setBackground(new java.awt.Color(255, 236, 236));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(247, 247, 247));
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new AbsoluteConstraints(20, 110, -1, 30));

        jButton9.setBackground(new java.awt.Color(247, 247, 247));
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setText("Eliminar");
        jPanel4.add(jButton9, new AbsoluteConstraints(20, 150, -1, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel31, new AbsoluteConstraints(0, 0, 220, 160));

        jPanel4.add(jPanel7, new AbsoluteConstraints(110, 20, 220, 160));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/leia.jpg"))); // NOI18N
        jPanel10.add(jLabel27, new AbsoluteConstraints(0, 0, 70, 70));

        jPanel4.add(jPanel10, new AbsoluteConstraints(20, 20, 70, 70));

        jPanel2.add(jPanel4, new AbsoluteConstraints(120, 170, 350, 200));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen9.png"))); // NOI18N
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new AbsoluteConstraints(-140, -140, -1, 710));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen9.png"))); // NOI18N
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14, new AbsoluteConstraints(680, 80, 650, 720));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 153));
        jLabel16.setText("ENCUENTRA A TU MEJOR AMIGO/A");
        jLabel16.setToolTipText("");
        jPanel3.add(jLabel16, new AbsoluteConstraints(330, 40, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 236, 236));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 20), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(255, 246, 246));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de mascota", "Perro", "Gato" }));
        jPanel6.add(jComboBox1, new AbsoluteConstraints(10, 50, 173, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 246, 246));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raza", "Mestizo", "Caniche", "Salchicha" }));
        jPanel6.add(jComboBox2, new AbsoluteConstraints(210, 50, 173, -1));

        jComboBox5.setBackground(new java.awt.Color(255, 246, 246));
        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño", "Chico", "Mediano", "Grande" }));
        jPanel6.add(jComboBox5, new AbsoluteConstraints(400, 50, 173, -1));

        jComboBox6.setBackground(new java.awt.Color(255, 246, 246));
        jComboBox6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño", "Chico", "Mediano", "Grande" }));
        jPanel6.add(jComboBox6, new AbsoluteConstraints(610, 50, 173, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 246, 246));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setText("Se lleva con otros animales?");
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox1, new AbsoluteConstraints(560, 90, 220, 30));

        jCheckBox3.setBackground(new java.awt.Color(255, 246, 246));
        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox3.setText("Desparacitado/a");
        jCheckBox3.setContentAreaFilled(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox3, new AbsoluteConstraints(160, 90, 140, 30));

        jCheckBox4.setBackground(new java.awt.Color(255, 246, 246));
        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox4.setText("Se lleva con niños?");
        jCheckBox4.setContentAreaFilled(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox4, new AbsoluteConstraints(350, 90, 170, 30));

        jCheckBox5.setBackground(new java.awt.Color(255, 246, 246));
        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox5.setText("Vacunas");
        jCheckBox5.setContentAreaFilled(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox5, new AbsoluteConstraints(20, 90, 100, 30));

        jButton3.setBackground(new java.awt.Color(255, 246, 246));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new AbsoluteConstraints(330, 130, 140, 30));

        jPanel3.add(jPanel6, new AbsoluteConstraints(130, 110, 790, 190));

        jPanel8.setBackground(new java.awt.Color(255, 236, 236));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new AbsoluteConstraints(130, 320, 790, 240));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen9.png"))); // NOI18N
        jLabel26.setToolTipText("");
        jPanel3.add(jLabel26, new AbsoluteConstraints(720, 110, 420, 720));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen9.png"))); // NOI18N
        jLabel21.setToolTipText("");
        jPanel3.add(jLabel21, new AbsoluteConstraints(-140, -140, -1, 710));

        jTabbedPane1.addTab("tab2", jPanel3);

        getContentPane().add(jTabbedPane1, new AbsoluteConstraints(340, 40, 1160, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALIRMouseMoved
        SALIR.setBackground(new Color(214,180,248));
    }//GEN-LAST:event_SALIRMouseMoved

    private void SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALIRMouseClicked
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SALIRMouseClicked

    private void SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALIRMouseExited
        SALIR.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_SALIRMouseExited

    private void HOMEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseMoved
        HOME.setBackground(new Color(214,180,248));
    }//GEN-LAST:event_HOMEMouseMoved

    private void HOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_HOMEMouseClicked

    private void HOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseExited
        HOME.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_HOMEMouseExited

    private void BUSCARMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARMouseMoved
        BUSCAR.setBackground(new Color(214,180,248));
    }//GEN-LAST:event_BUSCARMouseMoved

    private void BUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_BUSCARMouseClicked

    private void BUSCARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARMouseExited
        BUSCAR.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_BUSCARMouseExited

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MenuR MenuFrame = new MenuR();
        MenuFrame.setVisible(true);
        MenuFrame.pack();
        MenuFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BUSCAR;
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel SALIR;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
