package Frontend.LoginAndSignUp.src.loginandsignup;
import java.awt.Color;
/**

 *

 * @author audre

 */

public class Menu extends javax.swing.JFrame {



    /**

     * Creates new form Menu

     */

    public Menu() {

        initComponents();

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    

    private void initComponents() {



        jPanel1 = new javax.swing.JPanel();

        jLabel4 = new javax.swing.JLabel();

        jLabel3 = new javax.swing.JLabel();

        jLabel2 = new javax.swing.JLabel();

        SALIR = new javax.swing.JPanel();

        jLabel7 = new javax.swing.JLabel();

        jLabel8 = new javax.swing.JLabel();

        HOME = new javax.swing.JPanel();

        jLabel5 = new javax.swing.JLabel();

        jLabel6 = new javax.swing.JLabel();

        BUSCAR = new javax.swing.JPanel();

        jLabel9 = new javax.swing.JLabel();

        jLabel10 = new javax.swing.JLabel();

        jLabel1 = new javax.swing.JLabel();

        jTabbedPane1 = new javax.swing.JTabbedPane();

        jPanel2 = new javax.swing.JPanel();

        jLabel11 = new javax.swing.JLabel();

        jLabel14 = new javax.swing.JLabel();

        jLabel13 = new javax.swing.JLabel();

        jLabel12 = new javax.swing.JLabel();

        jLabel15 = new javax.swing.JLabel();

        jPanel3 = new javax.swing.JPanel();

        jLabel16 = new javax.swing.JLabel();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getContentPane().setLayout(new AbsoluteLayout());



        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 1080));

        jPanel1.setLayout(new AbsoluteLayout());



        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen3.png"))); // NOI18N

        jPanel1.add(jLabel4, new AbsoluteConstraints(110, 30, 140, 150));



        jLabel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setText("Audrey Barrientos");

        jPanel1.add(jLabel3, new AbsoluteConstraints(80, 180, -1, -1));



        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen2.jpg"))); // NOI18N

        jPanel1.add(jLabel2, new AbsoluteConstraints(0, 0, 360, 270));



        SALIR.setBackground(new java.awt.Color(247, 247, 247));

        SALIR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {

            public void mouseMoved(java.awt.event.MouseEvent evt) {

                SALIRMouseMoved(evt);

            }

        });

        SALIR.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                SALIRMouseClicked(evt);

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                SALIRMouseExited(evt);

            }

        });

        SALIR.setLayout(new AbsoluteLayout());



        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\audre\\OneDrive\\Documentos\\NetBeansProjects\\LoginAndSignUp\\src\\icon\\Imagen6.png")); // NOI18N

        SALIR.add(jLabel7, new AbsoluteConstraints(20, 30, -1, 50));



        jLabel8.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));

        jLabel8.setText("SALIR");

        SALIR.add(jLabel8, new AbsoluteConstraints(86, 50, 70, 20));



        jPanel1.add(SALIR, new AbsoluteConstraints(0, 490, 350, 110));



        HOME.setBackground(new java.awt.Color(247, 247, 247));

        HOME.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {

            public void mouseMoved(java.awt.event.MouseEvent evt) {

                HOMEMouseMoved(evt);

            }

        });

        HOME.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                HOMEMouseClicked(evt);

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                HOMEMouseExited(evt);

            }

        });

        HOME.setLayout(new AbsoluteLayout());



        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen4.png"))); // NOI18N

        HOME.add(jLabel5, new AbsoluteConstraints(20, 30, -1, 50));



        jLabel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setText("HOME");

        HOME.add(jLabel6, new AbsoluteConstraints(90, 50, 70, 20));



        jPanel1.add(HOME, new AbsoluteConstraints(0, 270, 350, 110));



        BUSCAR.setBackground(new java.awt.Color(247, 247, 247));

        BUSCAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {

            public void mouseMoved(java.awt.event.MouseEvent evt) {

                BUSCARMouseMoved(evt);

            }

        });

        BUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                BUSCARMouseClicked(evt);

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {

                BUSCARMouseExited(evt);

            }

        });

        BUSCAR.setLayout(new AbsoluteLayout());



        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen5.png"))); // NOI18N

        BUSCAR.add(jLabel9, new AbsoluteConstraints(20, 30, -1, 50));



        jLabel10.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));

        jLabel10.setText("BUSCAR UN AMIGO/A");

        BUSCAR.add(jLabel10, new AbsoluteConstraints(86, 50, 200, 20));



        jPanel1.add(BUSCAR, new AbsoluteConstraints(0, 380, 350, 110));



        getContentPane().add(jPanel1, new AbsoluteConstraints(0, 0, -1, 780));



        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen2.jpg"))); // NOI18N

        getContentPane().add(jLabel1, new AbsoluteConstraints(320, 0, 1180, 80));



        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));



        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new AbsoluteLayout());



        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N

        jLabel11.setForeground(new java.awt.Color(255, 153, 153));

        jLabel11.setText("BIENVENIDOS A PAW CONNECT");

        jPanel2.add(jLabel11, new AbsoluteConstraints(230, 40, -1, -1));



        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen9.png"))); // NOI18N

        jLabel14.setToolTipText("");

        jPanel2.add(jLabel14, new AbsoluteConstraints(680, 80, 650, 720));



        jLabel13.setBackground(new java.awt.Color(255, 204, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen7.png"))); // NOI18N

        jPanel2.add(jLabel13, new AbsoluteConstraints(90, 120, -1, -1));



        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen8.png"))); // NOI18N

        jPanel2.add(jLabel12, new AbsoluteConstraints(140, 310, -1, -1));



        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Imagen9.png"))); // NOI18N

        jLabel15.setToolTipText("");

        jPanel2.add(jLabel15, new AbsoluteConstraints(-140, -140, -1, 710));



        jTabbedPane1.addTab("tab1", jPanel2);



        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setLayout(new AbsoluteLayout());



        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N

        jLabel16.setForeground(new java.awt.Color(255, 153, 153));

        jLabel16.setText("ENCUENTRA A TU FUTURO MEJOR AMIGO/A");

        jLabel16.setToolTipText("");

        jPanel3.add(jLabel16, new AbsoluteConstraints(320, 50, -1, -1));



        jTabbedPane1.addTab("tab2", jPanel3);



        getContentPane().add(jTabbedPane1, new AbsoluteConstraints(340, 40, 1160, 730));



        pack();

    }// </editor-fold>                        



    private void HOMEMouseClicked(java.awt.event.MouseEvent evt) {                                  

        jTabbedPane1.setSelectedIndex(0);

    }                                 



    private void HOMEMouseMoved(java.awt.event.MouseEvent evt) {                                

        HOME.setBackground(new Color(214,180,248));

    }                               



    private void HOMEMouseExited(java.awt.event.MouseEvent evt) {                                 

        HOME.setBackground(new Color(247,247,247));

    }                                



    private void BUSCARMouseClicked(java.awt.event.MouseEvent evt) {                                    

        jTabbedPane1.setSelectedIndex(1);

    }                                   



    private void BUSCARMouseMoved(java.awt.event.MouseEvent evt) {                                  

        BUSCAR.setBackground(new Color(214,180,248));

    }                                 



    private void BUSCARMouseExited(java.awt.event.MouseEvent evt) {                                   

        BUSCAR.setBackground(new Color(247,247,247));

    }                                  



    private void SALIRMouseClicked(java.awt.event.MouseEvent evt) {                                   

        System.exit(0);

    }                                  



    private void SALIRMouseExited(java.awt.event.MouseEvent evt) {                                  

       SALIR.setBackground(new Color(247,247,247));

    }                                 



    private void SALIRMouseMoved(java.awt.event.MouseEvent evt) {                                 

        SALIR.setBackground(new Color(214,180,248));

    }                                



    // Variables declaration - do not modify                     

    private javax.swing.JPanel BUSCAR;

    private javax.swing.JPanel HOME;

    private javax.swing.JPanel SALIR;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel10;

    private javax.swing.JLabel jLabel11;

    private javax.swing.JLabel jLabel12;

    private javax.swing.JLabel jLabel13;

    private javax.swing.JLabel jLabel14;

    private javax.swing.JLabel jLabel15;

    private javax.swing.JLabel jLabel16;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabel6;

    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JTabbedPane jTabbedPane1;

    // End of variables declaration                   

}

